// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanGame.Models;

#nullable disable

namespace WebBanGame.Migrations
{
    [DbContext(typeof(BanGameBanQuyenContext))]
    partial class BanGameBanQuyenContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanGame.Models.AccountAdmin", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(24)
                        .IsUnicode(false)
                        .HasColumnType("varchar(24)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("TaiKhoan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("AccountId")
                        .HasName("PK__AccountA__349DA586C498078D");

                    b.ToTable("AccountAdmin", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaCtdh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaCTDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCtdh"));

                    b.Property<int>("MaDh")
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    b.Property<int>("MaSp")
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    b.Property<int>("Ngaygiao")
                        .HasColumnType("int");

                    b.Property<int>("TongTien")
                        .HasColumnType("int");

                    b.HasKey("MaCtdh")
                        .HasName("PK__ChiTietD__1E4E40F05ACAC64D");

                    b.HasIndex("MaDh");

                    b.HasIndex("MaSp");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.DanhMucSp", b =>
                {
                    b.Property<int>("MaDm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDm"));

                    b.Property<string>("AnhDm")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhDM");

                    b.Property<string>("MoTaDm")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MoTaDM");

                    b.Property<string>("TenDm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenDM");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.HasKey("MaDm")
                        .HasName("PK__DanhMucS__2725866E4825DDF8");

                    b.ToTable("DanhMucSP", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.DonHang", b =>
                {
                    b.Property<int>("MaDh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaDH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDh"));

                    b.Property<int>("MaKh")
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    b.Property<DateOnly>("NgayTao")
                        .HasColumnType("date");

                    b.Property<DateOnly>("NgayThanhToan")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ThanhToan")
                        .HasColumnType("bit");

                    b.Property<bool>("TrangThaiHuyDon")
                        .HasColumnType("bit");

                    b.HasKey("MaDh")
                        .HasName("PK__DonHang__27258661FFFC2296");

                    b.HasIndex("MaKh");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaKH");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKh"));

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Diachi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly>("Ngaysinh")
                        .HasColumnType("date");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<decimal?>("SoDuTk")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("SoDuTK");

                    b.Property<string>("TenKh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKh")
                        .HasName("PK__KhachHan__2725CF1E0BBCEEB3");

                    b.ToTable("KhachHang", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.SanPham", b =>
                {
                    b.Property<int>("MaSp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("MaSP");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSp"));

                    b.Property<string>("AnhSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AnhSP");

                    b.Property<bool>("BestSeller")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<int>("GiaSp")
                        .HasColumnType("int")
                        .HasColumnName("GiaSP");

                    b.Property<string>("LinkDownGame")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDm")
                        .HasColumnType("int")
                        .HasColumnName("MaDM");

                    b.Property<string>("MotaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotaSP");

                    b.Property<DateOnly>("NgaySua")
                        .HasColumnType("date");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("TenSP");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit");

                    b.Property<string>("VideoSp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("VideoSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SanPham__2725081C37D0281D");

                    b.HasIndex("MaDm");

                    b.ToTable("SanPham", (string)null);
                });

            modelBuilder.Entity("WebBanGame.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanGame.Models.DonHang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__Ngayg__4316F928");

                    b.HasOne("WebBanGame.Models.SanPham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaSP__440B1D61");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("WebBanGame.Models.DonHang", b =>
                {
                    b.HasOne("WebBanGame.Models.KhachHang", "MaKhNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK_DonHang_KhachHang");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("WebBanGame.Models.SanPham", b =>
                {
                    b.HasOne("WebBanGame.Models.DanhMucSp", "MaDmNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDm")
                        .HasConstraintName("FK__SanPham__MotaSP__3B75D760");

                    b.Navigation("MaDmNavigation");
                });

            modelBuilder.Entity("WebBanGame.Models.DanhMucSp", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("WebBanGame.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("WebBanGame.Models.KhachHang", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanGame.Models.SanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
